CREATE TABLE IF NOT EXISTS products(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    book_title VARCHAR(255) NOT NULL,
    book_description VARCHAR(600) NOT NULL,
    book_cover VARCHAR(255) NOT NULL,
    book_link VARCHAR(255) NOT NULL
);

INSERT INTO products (book_title, book_description, book_cover, book_link) 
VALUES
('Harry Potter: The Prequel', 'The Harry Potter Prequel is an 800-word story written by J. K. Rowling, and was published online on June 11th, 2008. Set three years before the birth of Harry Potter, the story recounts an adventure had by Sirius Black and James Potter.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1456894457i/8933944._SY180_.jpg', 'https://www.goodreads.com/book/show/8933944-harry-potter'),
('Harry Potter and the Philosophers Stone', 'Harry Potter thinks he is an ordinary boy - until he is rescued by an owl, taken to Hogwarts School of Witchcraft and Wizardry, learns to play Quidditch and does battle in a deadly duel. The Reason ... HARRY POTTER IS A WIZARD!', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1170803558l/72193._SX120_SY180_.jpg', 'https://www.goodreads.com/book/show/72193.Harry_Potter_and_the_Philosopher_s_Stone'),
('Harry Potter and the Chamber of Secrets', 'For in Harrys second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls bathroom. But then the real trouble begins someone is turning Hogwarts students to stone.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474169725i/15881._SY180_.jpg', 'https://www.goodreads.com/book/show/15881.Harry_Potter_and_the_Chamber_of_Secrets'),
('Harry Potter and the Prisoner of Azkaban', 'Harry Potter, along with his best friends, Ron and Hermione, is about to start his third year at Hogwarts School of Witchcraft and Wizardry. Harry can not wait to get back to school after the summer holidays. (Who would not if they lived with the horrible Dursleys?) But when Harry gets to Hogwarts, the atmosphere is tense. There is an escaped mass murderer on the loose, and the sinister prison guards of Azkaban have been called in to guard the school...', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630547330i/5._SY180_.jpg', 'https://www.goodreads.com/book/show/5.Harry_Potter_and_the_Prisoner_of_Azkaban'),
('Harry Potter and the Goblet of Fire', 'It is the summer holidays and soon Harry Potter will be starting his fourth year at Hogwarts School of Witchcraft and Wizardry. Harry is counting the days: there are new spells to be learnt, more Quidditch to be played, and Hogwarts castle to continue exploring. But Harry needs to be careful - there are unexpected dangers lurking...', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1554006152i/6._SX120_.jpg', 'https://www.goodreads.com/book/show/6.Harry_Potter_and_the_Goblet_of_Fire'),
('Harry Potter and the Order of the Phoenix', 'Harry Potter is about to start his fifth year at Hogwarts School of Witchcraft and Wizardry. Unlike most schoolboys, Harry never enjoys his summer holidays, but this summer is even worse than usual. The Dursleys, of course, are making his life a misery, but even his best friends, Ron and Hermione, seem to be neglecting him.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1660911061i/2._SY180_.jpg', 'https://www.goodreads.com/book/show/2.Harry_Potter_and_the_Order_of_the_Phoenix'),
('Harry Potter and the Half-Blood Prince', 'It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys house in Privet Drive for a visit from Professor Dumbledore himself.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1587697303i/1._SX120_.jpg', 'https://www.goodreads.com/book/show/1.Harry_Potter_and_the_Half_Blood_Prince'),
('Harry Potter and the Deathly Hallows', 'Harry has been burdened with a dark, dangerous and seemingly impossible task: that of locating and destroying Voldemorts remaining Horcruxes. Never has Harry felt so alone, or faced a future so full of shadows. But Harry must somehow find within himself the strength to complete the task he has been given. He must leave the warmth, safety and companionship of The Burrow and follow without fear or hesitation the inexorable path laid out for him...', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1663805647i/136251._SY180_.jpg', 'https://www.goodreads.com/book/show/136251.Harry_Potter_and_the_Deathly_Hallows'),
('Harry Potter and the Cursed Child: Parts One and Two', 'It was always difficult being Harry Potter, and it is not much easier now that he is an overworked employee of the Ministry of Magic, a husband, and a father of three school-age children. While Harry grapples with a past that refuses to stay where it belongs, his youngest son, Albus, must struggle with the weight of a family legacy he never wanted. As past and present fuse ominously, both father and son learn the uncomfortable truth: sometimes, darkness comes from unexpected places.', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1663805647i/136251._SY180_.jpg', 'https://www.goodreads.com/book/show/136251.Harry_Potter_and_the_Deathly_Hallows')